### ISSUE TITLE
Error parsing hardlinks

### ISSUE THREAD

**Issue by rgamez** [iemejia/catho#25]
Not such file or directory while parsing a hardlink

$ ls -al ~/Dropbox/iPad/
lrwxr-xr-x    1 rgamez  staff        38 18 feb  2012 test.pdf -> /Users/rgamez/Documents/test.pdf

$ ./catho.py add iPad ~/Dropbox/iPad
Creating catalog: iPad
An error occurred: [Errno 2] No such file or directory: '/Users/rgamez/Dropbox/iPad/test.pdf'

**Comment by iemejia** [comment]
wasn't that a softlink ?
errorno: 2 means that the target file doesn't exist, I just added some code that warns about this.
can you confirm me that this is the issue ?

**Comment by rgamez** [comment]
It is an issue with orphan symbolic links on my filesystem.
