### ISSUE TITLE
refactor to pep-8 standard

### ISSUE THREAD

**Issue by iemejia** [iemejia/catho#5]

**Comment by rgamez** [comment]
Solved in commit 43bac521c48fcb845cd63bd81c7601b7e32a78fa

**Comment by iemejia** [comment]
utils and init files are missing

**Comment by iemejia** [comment]
please change from list to ls (new format), that closes another issue too :)

**Comment by rgamez** [comment]
Pushed on dc5eb047de562bdded026e7892fe74a9a6cc8332

**Comment by iemejia** [comment]
It also fixes Fixes #8
